[project]
name = "smartstore-chatbot"
version = "0.1.0"
requires-python = ">=3.12"

[tool.pytest.ini_options]
pythonpath = "."

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["E501"]